###
POST http://localhost:8080/auth/registration
Content-Type: application/json
Authorization:

{
  "phone": "998337806712",
  "name": "Bahodir",
  "surname": "Hurramov",
  "email": "bahodirmufid@gmail.com",
  "password": "1111",
  "photoId" : "fc2f7ce8-6c9c-4439-bb68-de9429b3ef3d"
}



###MODERATOR
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "bahodir@gmail.com",
  "password": "1111"
}

###USER
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "qobil@gmail.com",
  "password": "1111"
}

###ADMIN
POST http://localhost:8080/auth/login
Content-Type: application/json


{
  "email": "qobil@gmail.com",
  "password": "1111"
}

###PUBLISHER
POST http://localhost:8080/auth/login
Content-Type: application/json


{
  "email": "bahodir@gmail.com",
  "password": "1111"
}

###//admin update profile
PUT http://localhost:8080/profile/update/{{id}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyMDk4MDksImV4cCI6MTY1NTIxMzQwOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.X3Yo3oCt1oFliYff377WVJ1RPOgFY-sbJ-aV_oD3LsM

{
  "name": "jalol",
  "surName": "karshiboyev",
  "email": "kkk.com007",
  "phone": "998945779598"
}

###//admin delete profile
PUT http://localhost:8080/profile/delete/id
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyMDk4MDksImV4cCI6MTY1NTIxMzQwOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.X3Yo3oCt1oFliYff377WVJ1RPOgFY-sbJ-aV_oD3LsM


###
GET http://localhost:8080/profile/pagination
Content-Type: application/json
Authorization:

